services:
  - type: web
    name: quick-transfert
    env: python
    region: frankfurt
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn quick_transfert.wsgi --workers 1
    healthCheckPath: /
    envVars:
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: quick_transfert_db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*.render.com"

databases:
  - name: quick_transfert_db
    databaseName: quick_transfert
    user: postgres
    region: frankfurt
