# Generated by Django 4.2.9 on 2026-05-02 15:39

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMINISTRATEUR", "Administrateur"),
                            ("AGENT", "Agent"),
                            ("ASSOCIE", "Associé"),
                            ("INVESTISSEUR", "Investisseur"),
                        ],
                        default="AGENT",
                        max_length=20,
                        verbose_name="Rôle",
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profiles/",
                        verbose_name="Photo de profil",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Compte actif"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Caisse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "solde",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="Solde",
                    ),
                ),
                (
                    "agent",
                    models.OneToOneField(
                        limit_choices_to={"role__in": ["AGENT", "ADMINISTRATEUR"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caisse",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caisse",
                "verbose_name_plural": "Caisses",
            },
        ),
        migrations.CreateModel(
            name="ContratPartenaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_contrat",
                    models.CharField(
                        choices=[
                            ("ASSOCIE", "Associé"),
                            ("INVESTISSEUR", "Investisseur"),
                        ],
                        max_length=20,
                        verbose_name="Type de contrat",
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Date de début")),
                (
                    "duree_mois",
                    models.IntegerField(
                        blank=True,
                        help_text="Surtout pour les investisseurs",
                        null=True,
                        verbose_name="Durée (mois)",
                    ),
                ),
                (
                    "montant_engage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Montant engagé / investi",
                    ),
                ),
                (
                    "retour_attendu",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Retour attendu (fixes ou %)",
                    ),
                ),
                (
                    "montant_paye",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="Montant déjà payé",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        default="ACTIF", max_length=20, verbose_name="Statut"
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrat Partenaire",
                "verbose_name_plural": "Contrats Partenaires",
            },
        ),
        migrations.CreateModel(
            name="Devise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=3,
                        unique=True,
                        verbose_name="Code devise (ex: USD, EUR)",
                    ),
                ),
                (
                    "taux_reference_usd",
                    models.DecimalField(
                        decimal_places=4,
                        default=1.0,
                        max_digits=10,
                        verbose_name="Taux par rapport à l'USD",
                    ),
                ),
            ],
            options={
                "verbose_name": "Devise",
                "verbose_name_plural": "Devises",
            },
        ),
        migrations.CreateModel(
            name="ZoneTarif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="Nom de la zone (ex: Nord-Congo)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zone Tarifaire",
                "verbose_name_plural": "Zones Tarifaires",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_transaction",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="N° Transaction"
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date et Heure"
                    ),
                ),
                (
                    "type_operation",
                    models.CharField(
                        choices=[("TRANSFERT", "Transfert"), ("RETRAIT", "Retrait")],
                        max_length=20,
                        verbose_name="Type d'opération",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Montant"
                    ),
                ),
                (
                    "taux_conversion",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Taux vers la devise de réf.",
                        max_digits=10,
                        verbose_name="Taux appliqué",
                    ),
                ),
                (
                    "frais_calcules",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Frais calculés"
                    ),
                ),
                (
                    "montant_reference",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Montant (Réf. USD)",
                    ),
                ),
                (
                    "frais_reference",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Frais (Réf. USD)",
                    ),
                ),
                (
                    "observation",
                    models.TextField(blank=True, verbose_name="Observation"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("COMPLETED", "Terminé"), ("ANNULÉ", "Annulé")],
                        default="COMPLETED",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "motif_annulation",
                    models.TextField(blank=True, verbose_name="Motif d'annulation"),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["AGENT", "ADMINISTRATEUR"]},
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Agent",
                    ),
                ),
                (
                    "devise_origine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="trans_origine",
                        to="core.devise",
                        verbose_name="Devise d'origine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Tarif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant_min",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant Minimum"
                    ),
                ),
                (
                    "montant_max",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant Maximum"
                    ),
                ),
                (
                    "frais_fixe",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Frais Fixe"
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifs",
                        to="core.zonetarif",
                        verbose_name="Zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarif",
                "verbose_name_plural": "Tarifs",
                "ordering": ["zone", "montant_min"],
            },
        ),
        migrations.CreateModel(
            name="SessionCaisse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_ouverture",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Heure d'ouverture"
                    ),
                ),
                (
                    "date_fermeture",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Heure de fermeture"
                    ),
                ),
                (
                    "solde_initial",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Solde initial"
                    ),
                ),
                (
                    "solde_final_theorique",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Solde final attendu",
                    ),
                ),
                (
                    "cash_declare",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Cash déclaré (Physique)",
                    ),
                ),
                (
                    "ecart",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Écart de caisse",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("OUVERT", "Ouvert"), ("FERMÉ", "Fermé")],
                        default="OUVERT",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["AGENT", "ADMINISTRATEUR"]},
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="sessions_caisse",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Agent",
                    ),
                ),
                (
                    "caisse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="core.caisse",
                        verbose_name="Caisse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session de Caisse",
                "verbose_name_plural": "Sessions de Caisse",
                "ordering": ["-date_ouverture"],
            },
        ),
        migrations.CreateModel(
            name="PaiementPartenaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Date de paiement"
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Montant payé"
                    ),
                ),
                (
                    "observation",
                    models.TextField(blank=True, verbose_name="Observation"),
                ),
                (
                    "contrat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements",
                        to="core.contratpartenaire",
                        verbose_name="Contrat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement Partenaire",
                "verbose_name_plural": "Paiements Partenaires",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=255, verbose_name="Message")),
                ("is_read", models.BooleanField(default=False, verbose_name="Lue")),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalTransaction",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "numero_transaction",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="N° Transaction"
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Date et Heure"
                    ),
                ),
                (
                    "type_operation",
                    models.CharField(
                        choices=[("TRANSFERT", "Transfert"), ("RETRAIT", "Retrait")],
                        max_length=20,
                        verbose_name="Type d'opération",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Montant"
                    ),
                ),
                (
                    "taux_conversion",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Taux vers la devise de réf.",
                        max_digits=10,
                        verbose_name="Taux appliqué",
                    ),
                ),
                (
                    "frais_calcules",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Frais calculés"
                    ),
                ),
                (
                    "montant_reference",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Montant (Réf. USD)",
                    ),
                ),
                (
                    "frais_reference",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Frais (Réf. USD)",
                    ),
                ),
                (
                    "observation",
                    models.TextField(blank=True, verbose_name="Observation"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("COMPLETED", "Terminé"), ("ANNULÉ", "Annulé")],
                        default="COMPLETED",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "motif_annulation",
                    models.TextField(blank=True, verbose_name="Motif d'annulation"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={"role__in": ["AGENT", "ADMINISTRATEUR"]},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Agent",
                    ),
                ),
                (
                    "devise_origine",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.devise",
                        verbose_name="Devise d'origine",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Transaction",
                "verbose_name_plural": "historical Transactions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCustomUser",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True,
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMINISTRATEUR", "Administrateur"),
                            ("AGENT", "Agent"),
                            ("ASSOCIE", "Associé"),
                            ("INVESTISSEUR", "Investisseur"),
                        ],
                        default="AGENT",
                        max_length=20,
                        verbose_name="Rôle",
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "photo",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Photo de profil",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Compte actif"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical user",
                "verbose_name_plural": "historical users",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCaisse",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "solde",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="Solde",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={"role__in": ["AGENT", "ADMINISTRATEUR"]},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Agent",
                    ),
                ),
                (
                    "devise",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.devise",
                        verbose_name="Devise de la caisse",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Caisse",
                "verbose_name_plural": "historical Caisses",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Depense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="Date")),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant"
                    ),
                ),
                ("motif", models.CharField(max_length=255, verbose_name="Motif")),
                (
                    "categorie",
                    models.CharField(max_length=100, verbose_name="Catégorie"),
                ),
                (
                    "destination",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Destination"
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="Commentaire"),
                ),
                (
                    "justificatif",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="depenses/",
                        verbose_name="Justificatif (PDF/Image)",
                    ),
                ),
                (
                    "devise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.devise",
                        verbose_name="Devise",
                    ),
                ),
                (
                    "enregistre_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Enregistré par (Admin)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dépense",
                "verbose_name_plural": "Dépenses",
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="contratpartenaire",
            name="devise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="core.devise",
                verbose_name="Devise",
            ),
        ),
        migrations.AddField(
            model_name="contratpartenaire",
            name="partenaire",
            field=models.ForeignKey(
                limit_choices_to={"role__in": ["ASSOCIE", "INVESTISSEUR"]},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contrats",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Partenaire",
            ),
        ),
        migrations.AddField(
            model_name="caisse",
            name="devise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="core.devise",
                verbose_name="Devise de la caisse",
            ),
        ),
        migrations.CreateModel(
            name="AgentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commission_pourcentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="Pourcentage de commission (%)",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil Agent",
                "verbose_name_plural": "Profils Agents",
            },
        ),
    ]
