# Generated by Django 4.2.9 on 2026-05-02 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant_commission",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Montant commission",
                    ),
                ),
                (
                    "pourcentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Pourcentage appliqué",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de calcul"
                    ),
                ),
                (
                    "statut_paiement",
                    models.CharField(
                        choices=[("IMPAYEE", "Non payée"), ("PAYEE", "Payée")],
                        default="IMPAYEE",
                        max_length=20,
                        verbose_name="Statut de paiement",
                    ),
                ),
                (
                    "date_paiement",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de paiement"
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["AGENT"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Agent",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="commissions",
                        to="core.transaction",
                        verbose_name="Transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commission",
                "verbose_name_plural": "Commissions",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="AgentActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("TRANSACTION_CREATE", "Transaction créée"),
                            ("TRANSACTION_CANCEL", "Transaction annulée"),
                            ("SESSION_OPEN", "Session ouverte"),
                            ("SESSION_CLOSE", "Session fermée"),
                            ("LOGIN", "Connexion"),
                            ("LOGOUT", "Déconnexion"),
                        ],
                        max_length=50,
                        verbose_name="Action",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date/Heure"),
                ),
                (
                    "ip_address",
                    models.CharField(
                        blank=True, max_length=45, verbose_name="Adresse IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "agent",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["AGENT"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal d'activité agent",
                "verbose_name_plural": "Journaux d'activité agents",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AgentPerformanceMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "total_transactions",
                    models.IntegerField(default=0, verbose_name="Nombre transactions"),
                ),
                (
                    "total_transfers",
                    models.IntegerField(default=0, verbose_name="Transferts"),
                ),
                (
                    "total_withdrawals",
                    models.IntegerField(default=0, verbose_name="Retraits"),
                ),
                (
                    "total_volume",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="Volume total (USD)",
                    ),
                ),
                (
                    "total_fees",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Frais totaux (USD)",
                    ),
                ),
                (
                    "total_commissions",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Commissions (USD)",
                    ),
                ),
                (
                    "average_transaction",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="Montant moyen transaction (USD)",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["AGENT"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_metrics",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Métriques performances agent",
                "verbose_name_plural": "Métriques performances agents",
                "ordering": ["-date"],
                "unique_together": {("agent", "date")},
            },
        ),
    ]
