# Generated by Django 4.2.9 on 2026-05-03 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_commission_agentactivitylog_agentperformancemetrics"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Création"),
                            ("EDIT", "Modification"),
                            ("CANCEL", "Annulation"),
                            ("VERIFY", "Vérification"),
                            ("APPROVE", "Approbation"),
                        ],
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Anciennes valeurs"
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Nouvelles valeurs"
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Raison")),
                (
                    "ip_address",
                    models.CharField(
                        blank=True, max_length=45, verbose_name="Adresse IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Effectué par",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audits",
                        to="core.transaction",
                        verbose_name="Transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Transaction",
                "verbose_name_plural": "Audits Transaction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        default="Rapid Cash",
                        max_length=255,
                        verbose_name="Nom de l'entreprise",
                    ),
                ),
                (
                    "company_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Téléphone de l'entreprise",
                    ),
                ),
                (
                    "company_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email de l'entreprise"
                    ),
                ),
                (
                    "company_address",
                    models.TextField(
                        blank=True, verbose_name="Adresse de l'entreprise"
                    ),
                ),
                (
                    "default_commission_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        max_digits=5,
                        verbose_name="Commission par défaut (%)",
                    ),
                ),
                (
                    "transaction_number_prefix",
                    models.CharField(
                        default="TX",
                        max_length=10,
                        verbose_name="Préfixe numéro transaction",
                    ),
                ),
                (
                    "enable_email_notifications",
                    models.BooleanField(
                        default=False, verbose_name="Activer notifications email"
                    ),
                ),
                (
                    "enable_sms_notifications",
                    models.BooleanField(
                        default=False, verbose_name="Activer notifications SMS"
                    ),
                ),
                (
                    "enable_api",
                    models.BooleanField(default=False, verbose_name="Activer API REST"),
                ),
                (
                    "is_maintenance_mode",
                    models.BooleanField(default=False, verbose_name="Mode maintenance"),
                ),
                (
                    "maintenance_message",
                    models.TextField(blank=True, verbose_name="Message maintenance"),
                ),
                (
                    "enable_audit_trail",
                    models.BooleanField(
                        default=True, verbose_name="Enregistrer les audits"
                    ),
                ),
                (
                    "audit_retention_days",
                    models.IntegerField(
                        default=365, verbose_name="Jours rétention audits"
                    ),
                ),
                (
                    "auto_reconcile_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        max_digits=10,
                        verbose_name="Seuil auto-réconciliation (USD)",
                    ),
                ),
                (
                    "require_manager_approval",
                    models.BooleanField(
                        default=False, verbose_name="Approbation manager requise"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settings_updates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètres Système",
                "verbose_name_plural": "Paramètres Système",
            },
        ),
        migrations.CreateModel(
            name="APIToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(max_length=255, unique=True, verbose_name="Token"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière utilisation"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expire le"
                    ),
                ),
                (
                    "can_view_transactions",
                    models.BooleanField(default=True, verbose_name="Voir transactions"),
                ),
                (
                    "can_create_transactions",
                    models.BooleanField(
                        default=False, verbose_name="Créer transactions"
                    ),
                ),
                (
                    "can_view_reports",
                    models.BooleanField(default=True, verbose_name="Voir rapports"),
                ),
                (
                    "can_manage_users",
                    models.BooleanField(
                        default=False, verbose_name="Gérer utilisateurs"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_token",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token API",
                "verbose_name_plural": "Tokens API",
            },
        ),
    ]
