# Generated by Django 6.0.5 on 2026-05-26 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_transactionaudit_systemsettings_apitoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="caisse",
            name="is_partner_caisse",
            field=models.BooleanField(
                default=False, verbose_name="Caisse partenaire (Associé)"
            ),
        ),
        migrations.AddField(
            model_name="contratpartenaire",
            name="capital_rembourse",
            field=models.BooleanField(default=False, verbose_name="Capital remboursé"),
        ),
        migrations.AddField(
            model_name="contratpartenaire",
            name="date_remboursement",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de remboursement du capital"
            ),
        ),
        migrations.AddField(
            model_name="contratpartenaire",
            name="pourcentage_partage_rc",
            field=models.DecimalField(
                decimal_places=2,
                default=40.0,
                help_text="Pourcentage des bénéfices mensuels prélevé par Rapid Cash (par défaut 40%)",
                max_digits=5,
                verbose_name="% prélevé par Rapid Cash",
            ),
        ),
        migrations.AddField(
            model_name="contratpartenaire",
            name="rendement_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Rendement mensuel maximum (USD)",
            ),
        ),
        migrations.AddField(
            model_name="contratpartenaire",
            name="rendement_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Rendement mensuel minimum (USD)",
            ),
        ),
        migrations.AddField(
            model_name="historicalcaisse",
            name="is_partner_caisse",
            field=models.BooleanField(
                default=False, verbose_name="Caisse partenaire (Associé)"
            ),
        ),
        migrations.AlterField(
            model_name="caisse",
            name="agent",
            field=models.OneToOneField(
                limit_choices_to={"role__in": ["AGENT", "ADMINISTRATEUR", "ASSOCIE"]},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="caisse",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Agent/Associé",
            ),
        ),
        migrations.AlterField(
            model_name="contratpartenaire",
            name="duree_mois",
            field=models.IntegerField(
                blank=True,
                help_text="Durée du contrat",
                null=True,
                verbose_name="Durée (mois)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcaisse",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={"role__in": ["AGENT", "ADMINISTRATEUR", "ASSOCIE"]},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Agent/Associé",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltransaction",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={"role__in": ["AGENT", "ADMINISTRATEUR", "ASSOCIE"]},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Agent/Associé",
            ),
        ),
        migrations.AlterField(
            model_name="sessioncaisse",
            name="agent",
            field=models.ForeignKey(
                limit_choices_to={"role__in": ["AGENT", "ADMINISTRATEUR", "ASSOCIE"]},
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="sessions_caisse",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Agent/Associé",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="agent",
            field=models.ForeignKey(
                limit_choices_to={"role__in": ["AGENT", "ADMINISTRATEUR", "ASSOCIE"]},
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="transactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Agent/Associé",
            ),
        ),
        migrations.CreateModel(
            name="GainMensuelInvestisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mois", models.IntegerField(verbose_name="Mois")),
                ("annee", models.IntegerField(verbose_name="Année")),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Montant du gain (USD)",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("EN_ATTENTE", "En attente"), ("PAYE", "Payé")],
                        default="EN_ATTENTE",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_attribution",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'attribution"
                    ),
                ),
                (
                    "date_paiement",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de paiement"
                    ),
                ),
                (
                    "observation",
                    models.TextField(blank=True, verbose_name="Observation"),
                ),
                (
                    "attribue_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gains_attribues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Attribué par",
                    ),
                ),
                (
                    "contrat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gains_mensuels",
                        to="core.contratpartenaire",
                        verbose_name="Contrat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gain Mensuel Investisseur",
                "verbose_name_plural": "Gains Mensuels Investisseurs",
                "ordering": ["-annee", "-mois"],
                "unique_together": {("contrat", "mois", "annee")},
            },
        ),
        migrations.CreateModel(
            name="RapportMensuelAssocie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mois", models.IntegerField(verbose_name="Mois")),
                ("annee", models.IntegerField(verbose_name="Année")),
                (
                    "nombre_operations",
                    models.IntegerField(default=0, verbose_name="Nombre d'opérations"),
                ),
                (
                    "volume_operations",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="Volume total des opérations (USD)",
                    ),
                ),
                (
                    "total_frais_collectes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Total frais/commissions collectés",
                    ),
                ),
                (
                    "pourcentage_rc",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="% Rapid Cash appliqué",
                    ),
                ),
                (
                    "montant_rc",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Part Rapid Cash (USD)",
                    ),
                ),
                (
                    "montant_associe",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Part Associé (USD)",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("GENERE", "Généré"),
                            ("VALIDE", "Validé"),
                            ("PAYE", "Payé"),
                        ],
                        default="GENERE",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_generation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de génération"
                    ),
                ),
                (
                    "date_paiement",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de paiement RC"
                    ),
                ),
                (
                    "observation",
                    models.TextField(blank=True, verbose_name="Observation"),
                ),
                (
                    "contrat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rapports_mensuels",
                        to="core.contratpartenaire",
                        verbose_name="Contrat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport Mensuel Associé",
                "verbose_name_plural": "Rapports Mensuels Associés",
                "ordering": ["-annee", "-mois"],
                "unique_together": {("contrat", "mois", "annee")},
            },
        ),
    ]
